const student = [
    {
        id: 12,
        Name: 'Anamul Haque',
        Loc: 'Savar, Dhaka',
        Gender: 'Male',
        age: 24,
        img: 'https://images.pexels.com/photos/3760539/pexels-photo-3760539.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 33,
            En: 40,
            Math: 45,
            S: 85,
            SS: 78,
            Rel: 85,
        },
    },
    {
        id: 1,
        Name: 'Rakib Adnan',
        Loc: 'Bogura',
        Gender: 'Male',
        age: 24,
        img: 'https://images.pexels.com/photos/8443969/pexels-photo-8443969.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 33,
            En: 40,
            Math: 45,
            S: 85,
            SS: 78,
            Rel: 85,
        },
    },
    {
        id: 2,
        Name: 'Priyaka das',
        Loc: 'Magura',
        Gender: 'Female',
        age: 24,
        img: 'https://images.pexels.com/photos/3014853/pexels-photo-3014853.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 75,
            En: 74,
            Math: 87,
            S: 52,
            SS: 40,
            Rel: 30,
        },
    },
    {
        id: 3,
        Name: 'Uttam Kimar',
        Loc: 'Natore',
        Gender: 'Male',
        age: 24,
        img: 'https://images.pexels.com/photos/3217111/pexels-photo-3217111.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 85,
            En: 49,
            Math: 76,
            S: 75,
            SS: 94,
            Rel: 65,
        },
    },
    {
        id: 4,
        Name: 'Mamun Islam',
        Loc: 'Rangpur',
        Gender: 'Male',
        age: 24,
        img: 'https://images.pexels.com/photos/3480329/pexels-photo-3480329.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 65,
            En: 85,
            Math: 76,
            S: 78,
            SS: 52,
            Rel: 75,
        },
    },
    {
        id: 5,
        Name: 'Abu sayeed',
        Loc: 'Cumilla',
        Gender: 'Male',
        age: 24,
        img: 'https://images.pexels.com/photos/3775582/pexels-photo-3775582.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 95,
            En: 62,
            Math: 89,
            S: 63,
            SS: 75,
            Rel: 61,
        },
    },
    {
        id: 6,
        Name: 'Yameen Hossain',
        Loc: 'Bogura',
        Gender: 'Male',
        age: 24,
        img: 'https://images.pexels.com/photos/3724372/pexels-photo-3724372.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 85,
            En: 65,
            Math: 41,
            S: 45,
            SS: 52,
            Rel: 40,
        },
    },
    {
        id: 7,
        Name: 'Soniya Bariki',
        Loc: 'Netrokona',
        Gender: 'Female',
        age: 24,
        img: 'https://images.pexels.com/photos/7222852/pexels-photo-7222852.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 39,
            En: 50,
            Math: 78,
            S: 49,
            SS: 40,
            Rel: 45,
        },
    },
    {
        id: 8,
        Name: 'Ratna Akter',
        Loc: 'Dhunot',
        Gender: 'Female',
        age: 24,
        img: 'https://images.pexels.com/photos/4522534/pexels-photo-4522534.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 51,
            En: 45,
            Math: 85,
            S: 74,
            SS: 41,
            Rel: 42,
        },
    },
    {
        id: 10,
        Name: 'Sayeem',
        Loc: 'Kuri-Gram',
        Gender: 'Male',
        age: 24,
        img: 'https://images.pexels.com/photos/8584505/pexels-photo-8584505.png?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 77,
            En: 65,
            Math: 45,
            S: 42,
            SS: 65,
            Rel: 74,
        },
    },
    {
        id: 11,
        Name: 'Humayra',
        Loc: 'Rajshahi',
        Gender: 'Female',
        age: 24,
        img: 'https://images.pexels.com/photos/4347368/pexels-photo-4347368.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 65,
            En: 88,
            Math: 65,
            S: 72,
            SS: 58,
            Rel: 60,
        },
    },
    {
        id: 13,
        Name: 'Anamul Haque',
        Loc: 'Savar, Dhaka',
        Gender: 'Male',
        age: 24,
        img: 'https://images.pexels.com/photos/3760539/pexels-photo-3760539.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        marks: {
            Bn: 33,
            En: 40,
            Math: 45,
            S: 85,
            SS: 78,
            Rel: 85,
        },
    },
];
